AllCops:
  NewCops: enable

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 500
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

plugins:
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

